import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quadrant MSL Website",
  description: "Generated by create next app",
};

const satoshi = localFont({
  src: [
    {
      path: "../font/satoshi-Variable.ttf",
      style: "normal",
    },
    {
      path: "../font/satoshi-VariableItalic.ttf",
      style: "italic",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.className} font-sans`}
        suppressHydrationWarning={true}
      >
        <NavBar />

        <main className="min-h-screen">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
